export const metadata = {
  title: "Marketer | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="home">
      <h1>Home</h1>
    </div>
  );
}
