import Banner from "./components/home/banner";

export const metadata = {
  title: "Marketer | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="home">
      <Banner />
    </div>
  );
}
